### ISSUE TITLE
Installation requires external packages

### ISSUE THREAD

**Issue by LourensVeen** [xenon-middleware/pyxenon#29]
According to the installation instructions, `pip install pyxenon` should install pyxenon. This fails for me on Ubuntu 16.04 with several compilation errors regarding missing OpenSSL and libFFI headers. Doing `apt install libssl-dev libffi-dev` before `pip install pyxenon` fixes the issue.

**Comment by jhidding** [comment]
Darn, this is due to the `cryptography` library which is a dependency of `pyopenssl`. It's curious why your installation doesn't fall back on the wheel. From the `cryptography` readme: 

> cryptography ships a manylinux1 wheel (as of 2.0) so all dependencies are included. For users on pip 8.1 or above running on a manylinux1 compatible distribution (almost everything except Alpine) all you should need to do is:
> ```
> $ pip install cryptography
> ``` 

Or as a fallback:
> ```
> sudo apt-get install build-essential libssl-dev libffi-dev python3-dev
> ```

is needed on Ubuntu.
