### ISSUE TITLE
bin/xenon-grpc.bat missing

### ISSUE THREAD

**Issue by h4nsu** [xenon-middleware/pyxenon#33]
Hi Johan,
Trying to install the package on Windows fails due to ``xenon-grpc.bat`` not present in ``bin``. Can we expect this being fixed in the near future?

**Comment by jhidding** [comment]
Hi Michal,
I will take a look at it.

**Comment by jhidding** [comment]
If you start an interactive python and do
```
>>> import os
>>> os.name
```
What do you get? I expect either `posix`, in which case the bash script is copied, or `nt`, resulting in an install of `xenon-grpc.bat`.

**Comment by h4nsu** [comment]
I get ``nt``, but the file mentioned for ``nt`` in ``setup.py`` (``xenon-grpc.bat``) is simply not present in pyxenon/bin.

**Comment by h4nsu** [comment]
Ok, I think I know where the problem lies. I have a tarball downloaded with ``pip download`` on Linux and I tried to use it on Windows. My bad. Closing this one

**Comment by h4nsu** [comment]
But still, the tarball available on PyPI simply does not have the .bat file

**Comment by jhidding** [comment]
Sorry for the long wait. The issue is fixed now with the latest 3.0.3 release.
