### ISSUE TITLE
asynchronous job submission and status checking

### ISSUE THREAD

**Issue by usevani** [xenon-middleware/pyxenon#34]
Hi, 

This is more of a question than an issue. Wasn't really sure where to post, so apologies if this is not the right platform. 
I am setting up an application where job submissions and checking job status are handled by different processes. Process-1 essentially creates a JobDescription object, connects to an existing xenon instance,  instantiates scheduler, submits the JobDescription object and updates a db with Job.id. Process-2 will connect to the same xenon instance, instantiate scheduler and check the status of the job ids stored in db. 
The issue is that scheduler instance in process-2 does not recognize the job ids. Is this possible to do this using the library? Happy to post the code if it helps.

**Comment by jhidding** [comment]
This should be possible if you set the port number fixed. The second instance should detect the `xenon-grpc` already running and then connecting to that. Does that help?

**Comment by usevani** [comment]
I am setting the port, so both the processes are connecting to the same xenon server. But the Scheduler instances in process 1 and process 2 are different and don't recognize the Job.

**Comment by usevani** [comment]
Thank you! That's what i was looking for.
