### ISSUE TITLE
xenon.exceptions.UnknownRpcException: Xenon (StatusCode.UNAVAILABLE): "Connect Failed" in create

### ISSUE THREAD

**Issue by marksantcroos** [xenon-middleware/pyxenon#38]
Last week I reported success, and while trying to do the same thing on some other machines, I noticed that I actually can't get anything done there.
Although I did the installation in a similar way, both in a conda environment with python 3.

I brought my example back to the bare minimum (I think) and can reproduce the error on multiple Linux systems.

It seems there is a communication problem between the grpc client and server on those systems.

Code and output below. Do you have any suggestions on how to debug further?

Thanks!

``` python
import xenon

xenon.init(log_level="DEBUG")

job_description = xenon.JobDescription(
    executable='/bin/bash', 
    arguments=['-c', 'echo "Hello, World!"'],
)

with xenon.Scheduler.create(adaptor='local') as scheduler:
    job = scheduler.submit_batch_job(job_description)
    job_status = scheduler.wait_until_done(job)

```

```
$ python min.py 
Starting Xenon-GRPC server.
[out] 16:20:19.825 [main] ERROR n.e.xenon.grpc.XenonServerWrapper - Server started, listening on port 42657 with mutual TLS
Connecting to server
Traceback (most recent call last):
  File "min.py", line 10, in <module>
    with xenon.Scheduler.create(adaptor='local') as scheduler:
  File "/home/masantcroos/miniconda3/envs/xenon/lib/python3.7/site-packages/xenon/oop.py", line 304, in static_method
    grpc_call(cls.__stub__(__server__), m, request))
  File "/home/masantcroos/miniconda3/envs/xenon/lib/python3.7/site-packages/xenon/oop.py", line 271, in grpc_call
    raise make_exception(method, e) from None
xenon.exceptions.UnknownRpcException: Xenon (StatusCode.UNAVAILABLE): "Connect Failed" in create
Terminating Xenon-GRPC server.
[err] *** shutting down gRPC server since JVM is shutting down
[err] *** server shut down
```

**Comment by jhidding** [comment]
Do I understand correctly that this only happens on *some* machines? I couldn't reproduce your error. What is different about these machines? Could you give some details (distro, java version, python version)?
One thing you could try is disabling TLS authentication with Xenon-GRPC.

```python
xenon.init(disable_tls=True)
```

Another thing you could try is to see if the Xenon CLI (https://github.com/xenon-middleware/xenon-cli) does work. The CLI also works on Xenon-GRPC.

**Comment by marksantcroos** [comment]
Yes, I'm now testing on a:

- Ubuntu 18.04.2 LTS
- Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
- Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
- Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:01:00) 

Disabling TLS makes the Python example work.

I've also tried the CLI, and that works without changes.

Does that indicate we should look at the Python layer thus?

**Comment by marksantcroos** [comment]
Hmmm, are you sure the CLI actually uses Xenon-GRPC? It seems it uses the Java library directly.

**Comment by marksantcroos** [comment]
Found the cause.

My systems have a shared filesystem. Apparently the keyset that is automagically generated into `$HOME/.config/xenon-grpc` is not compatible between systems.

So after I removed the keyset created on one system, it also works on the other system.

**Comment by marksantcroos** [comment]
Would you accept a PR to create a `xenon-grpc/$HOSTNAME.[crt|key]` keyset?

**Comment by jhidding** [comment]
Certainly!
